DROP DATABASE IF EXISTS FORMAGGI;
CREATE DATABASE FORMAGGI;

DROP TABLE IF EXISTS FORMAGGIO;
DROP TABLE IF EXISTS UMIDITA;
DROP TABLE IF EXISTS TEMPERATURA;
DROP TABLE IF EXISTS TIPO;
DROP TABLE IF EXISTS SCAFFALE;
DROP TABLE IF EXISTS SENSORE;

CREATE TABLE SCAFFALE( 
    ID INT(16) UNSIGNED AUTO_INCREMENT, 
    NOME VARCHAR(20) NOT NULL, 
    CONSTRAINT PK_SCAFFALE PRIMARY KEY (ID) 
);


CREATE TABLE TIPO(
    ID INT(16) UNSIGNED AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL,
    UMIDITA_MAX INT,
    UMIDITA_MIN INT,
    TEMPERATURA_MAX INT,
    TEMPERATURA_MIN INT,
    CONSTRAINT PK_TIPO PRIMARY KEY (ID)
);


CREATE TABLE SENSORE(
    ID INT(16) UNSIGNED AUTO_INCREMENT,
    CONSTRAINT PK_SENSORE PRIMARY KEY (ID)
);


CREATE TABLE UMIDITA(
    ID INT(16) UNSIGNED AUTO_INCREMENT,
    VALORE FLOAT,
    TEMPO DATE,
    SENSORE_ID INT(16) UNSIGNED,
    CONSTRAINT PK_UMIDITA PRIMARY KEY (ID),
    CONSTRAINT UMIDITA_FK_SENSORE_ID FOREIGN KEY (SENSORE_ID)
    REFERENCES SENSORE(ID)
);


CREATE TABLE TEMPERATURA(
    ID INT(16) UNSIGNED AUTO_INCREMENT,
    VALORE FLOAT,
    TEMPO DATE,
    SENSORE_ID INT(16) UNSIGNED,
    CONSTRAINT PK_TEMPERATURA PRIMARY KEY (ID),
    CONSTRAINT TEMPERATURA_FK_SENSORE_ID FOREIGN KEY (SENSORE_ID)
    REFERENCES SENSORE(ID)
);


CREATE TABLE FORMAGGIO( 
    ID INT(16) UNSIGNED AUTO_INCREMENT, 
    NOME VARCHAR(20) NOT NULL,
    TEMPO DATE, 
    SCAFFALE_ID INT(16) UNSIGNED,
    TIPO_ID INT(16) UNSIGNED,
    SENSORE_ID INT(16) UNSIGNED,
    CONSTRAINT PK_FORMAGGIO PRIMARY KEY (ID),
    CONSTRAINT FORAMGGIO_FK_SCAFFALE_ID FOREIGN KEY (SCAFFALE_ID)
    REFERENCES SCAFFALE(ID),
    CONSTRAINT FORMAGGIO_FK_TIPO_ID FOREIGN KEY(TIPO_ID)
    REFERENCES TIPO(ID),
    CONSTRAINT FORMAGGIO_FK_SENSORE_ID FOREIGN KEY (SENSORE_ID)
    REFERENCES SENSORE(ID)
);


--popolazione tipi
INSERT INTO `tipo` (`NOME`, `UMIDITA_MAX`, `UMIDITA_MIN`, `TEMPERATURA_MAX`, `TEMPERATURA_MIN`) VALUES ('parmigiano', '22', '15', '7', '-1');
INSERT INTO `tipo` (`NOME`, `UMIDITA_MAX`, `UMIDITA_MIN`, `TEMPERATURA_MAX`, `TEMPERATURA_MIN`) VALUES ('parmigianni', '67', '1', '18', '-273');
INSERT INTO `tipo` (`NOME`, `UMIDITA_MAX`, `UMIDITA_MIN`, `TEMPERATURA_MAX`, `TEMPERATURA_MIN`) VALUES ('brie', '50', '30', '12', '5');
INSERT INTO `tipo` (`NOME`, `UMIDITA_MAX`, `UMIDITA_MIN`, `TEMPERATURA_MAX`, `TEMPERATURA_MIN`) VALUES ('gorgonzola', '15', '7', '18', '-3');
INSERT INTO `tipo` (`NOME`, `UMIDITA_MAX`, `UMIDITA_MIN`, `TEMPERATURA_MAX`, `TEMPERATURA_MIN`) VALUES ('pecorino', '33', '22', '22', '3');